### ISSUE TITLE
add releases to github

### ISSUE THREAD

**Issue by yuriescl** [Arg0s1080/mrz#12]
There's no code release on this repository. Releases help developers get the source code of specific versions, usually when trying to look at the source code of a version from Pypi.  
If possible, please match the releases here with the releases of the Pypi package.

**Comment by Arg0s1080** [comment]
Hi

Yes, I should have done it. If I'm honest, I don't know how Github release system works. I will try to investigate how to do it.

Thanks a lot for the suggestion

**Comment by Arg0s1080** [comment]
Done!

Thanks!
