### ISSUE TITLE
Nonspecified sex should be < instead of X

### ISSUE THREAD

**Issue by jellevanwezel** [Arg0s1080/mrz#13]
According to page 14 of this ICAO document: [https://www.icao.int/publications/Documents/9303_p5_cons_en.pdf](https://www.icao.int/publications/Documents/9303_p5_cons_en.pdf)

Sex in the MRZ can be: `M` for male,`F` for female, and `<` for nonspecified.
However, the generator puts in a `X` for nonspecified instead of a `<`.

This is correct for the VIZ as can be seen in the same document at page 11.
But not for the MRZ.

The document refers to TD1 but it also aplies for the other document types:
* TD3: [https://www.icao.int/publications/Documents/9303_p4_cons_en.pdf](https://www.icao.int/publications/Documents/9303_p4_cons_en.pdf)
* TD2: [https://www.icao.int/publications/Documents/9303_p6_cons_en.pdf](https://www.icao.int/publications/Documents/9303_p6_cons_en.pdf)
* VISA: [https://www.icao.int/publications/Documents/9303_p7_cons_en.pdf](https://www.icao.int/publications/Documents/9303_p7_cons_en.pdf)

**Comment by Arg0s1080** [comment]
Hi @jellevanwezel !

Oops! Yes, it's a bug. It seems that I read the "F" note quickly and badly (my English is very bad, although the worst part is that the document is available in my language xD)

As always, thank you very much!

PS: I'll fix it as soon as I can, but have you not thought about creating your own PR?

**Comment by Arg0s1080** [comment]
Fixed!

Finally it will work as follows:

#### Generator:
Chars `F`, `f`, `M`, `m`, `X`, `x`, `<` and `""` (empty string) returns `<`, otherwise a `SexError` will rise

#### Checker:
Chars `M`, `F` or `<` returns `True`, `False` otherwise

Thanks
