### ISSUE TITLE
Code not executed after checker returns False

### ISSUE THREAD

**Issue by xxxpsyduck** [Arg0s1080/mrz#17]
Hello I have a code block like this:
```python
...
checker1 = TD3CodeChecker(...)

if bool(checker1) == True:
    ...
else:
   ...
```
The problem is when checker1 does not return True then all the lines below it won't run (the else statement never triggered).

**Comment by Arg0s1080** [comment]
Hi

I don't know if I understood you, but it works fine for me.

An example:

```python
from mrz.checker.td3 import TD3CodeChecker

# This MRZ code should return True 
mrz_td3 = ("P<CANMARTIN<<SARAH<<<<<<<<<<<<<<<<<<<<<<<<<<\n"
           "ZE000509<9CAN8501019F2301147<<<<<<<<<<<<<<08")

check1 = TD3CodeChecker(mrz_td3)

if bool(check1):
    print("check1 it's True")
else:
    print("check1 it's False")


# Now let's introduce some errors:
mrz_td3 = ("BDBADMARTIN<<SARAH<<<<<<<<<BAD<<<<BAD<<<<<<<\n"
           "ZE000509<1CAN8501019F2301147<<<<<<<<<<<<<<11")

check2 = TD3CodeChecker(mrz_td3)

if bool(check2) == True:
    print("check2 it's True")
else:
    print("check2 it's False")
```

Output:
```
check1 it's True
check2 it's False
```

Maybe if you showed the complete code we could see where is the error.

Regards!

**Comment by xxxpsyduck** [comment]
I have error with the following code:

`from mrz.checker.td3 import TD3CodeChecker

mrz_td3 = ("8053333LX2E7EZ90X2908022W6L0LL889SI95326S<2SL<\n"
           "333333333333333333233D13NVL13NX35ONV0317O19SI54")

check2 = TD3CodeChecker(mrz_td3)

if bool(check2) == True:
    print("check2 it's True")
else:
    print("check2 it's False")

# This MRZ code should return True 
mrz_td3 = ("P<CANMARTIN<<SARAH<<<<<<<<<<<<<<<<<<<<<<<<<<\n"
           "ZE000509<9CAN8501019F2301147<<<<<<<<<<<<<<08")

check1 = TD3CodeChecker(mrz_td3)

if bool(check1):
    print("check1 it's True")
else:
    print("check1 it's False")`

Output:

`raise LengthError(cause=len(s), document=document_description, length=length)
mrz.base.errors.LengthError: ('String was not recognized as a valid TD3. It should have 88 characters', '93')`

**Comment by xxxpsyduck** [comment]
@Arg0s1080 I modified your code to bypass all the exceptions. Btw there are some mistake in base/string_checkers.py, there is no name 's' defined in precheck() function

**Comment by Arg0s1080** [comment]
Hi again!

In the output you can see what the error is. Your mrz string has 93 chars. MRZ code of all TD3 must be 88 chars long (89 if escape character is counted)

So, as I see it, everything works fine.

Regards

**Comment by Hari95-creator** [comment]
hi I have the same error
def ocr(image):
    image=Image.open("mrzcode.png")
    text=tess.image_to_string("mrzcode.png")
    td3_check = TD3CodeChecker(text,compute_warnings=True)
    print(text)
    print(td3_check.mrz_code)

    fields = text.fields()

    print("Document Type:", fields.document_type)
    print("Country:", fields.country)
    print("Surname:", fields.surname)
    print("Name:", fields.name)
    print("Doc. Number", fields.document_number)
    print("Doc. Number Hash:", fields.document_number_hash)
    print("Nationality:", fields.nationality)
    print("Birth Date:", fields.birth_date)
    print("Birth Date Hash:", fields.birth_date_hash)
    print("Sex:", fields.sex)
    print("Expiry Date:", fields.expiry_date)
    print("Expiry Date Hash:", fields.expiry_date_hash)
    print("Optional data:", fields.optional_data)
    print("Optional data hash:", fields.optional_data_hash)
    print("Final Hash:", fields.final_hash)

 
  raise LengthError(cause=len(s), document=document_description, length=length)
mrz.base.errors.LengthError: ('String was not recognized as a valid TD3. It should have 89 characters', '90')
