### ISSUE TITLE
Mrz on windows: very slow the 1st time only

### ISSUE THREAD

**Issue by venkytt** [Arg0s1080/mrz#20]
Hello

mrz image.jpg > image.txt

takes about 8  - 10 seconds the 1st time for an image when that image is processed for the 1st time.  The 2nd time it is a lot more faster

How do I make it faster the 1st time? Should i keep any training data locally , or any other tips please?  

This is on windows 64 BIT with at least 10 GB virtual memory

Many Thanks

**Comment by Arg0s1080** [comment]
Hi, whats up

I'm very honored, but I´m afraid you are wrong. In effect the name of this project is mrz, but it is not capable of reading images. In the beginning I thought mrz was able to do it, but finally I focused only on strings.

Two things may have happened:
1 You are using a project with the same name
2 You are using a project that uses mrz as a dependency.

I hope you clear me up.

Regards!
