### ISSUE TITLE
Issue with georgia passports (td1)

### ISSUE THREAD

**Issue by ahvahsky2008** [Arg0s1080/mrz#23]
lib incorrect calc hash value. 
```
from mrz.generator.td1 import TD1CodeGenerator,dictionary

x1 = 'ID'
x2 = 'GEO'
x3 = '13IN30572'
x4 = '910526'
x5 = 'M'
x6 = '251221'
x7 = 'GEO'
x8 = 'MAMEDOV'
x9 = 'IUKSEL'
x10 ='10011051644'
dictionary.c
text = TD1CodeGenerator(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,force=False)
print(text)        
```
![image](https://user-images.githubusercontent.com/8035828/90067903-7881e400-dcf8-11ea-9cf8-565c66a2bdb3.png)

![image](https://user-images.githubusercontent.com/8035828/90067961-8f283b00-dcf8-11ea-8d5b-29a6119826a4.png)
![image](https://user-images.githubusercontent.com/8035828/90068045-b0892700-dcf8-11ea-80ab-ba577f9f4d7b.png)

**Comment by Arg0s1080** [comment]
Hi!

It seems odd. When I have a little free time I'll check it out (this weekend)

Regards

**Comment by Arg0s1080** [comment]
Checked!

Hash calc is correct

**You had a typo**. If you change `10011051644` by `10001051644` in optional_data field your output will be:

```python
from mrz.generator.td1 import TD1CodeGenerator

x1 = 'ID'
x2 = 'GEO'
x3 = '13IN30572'
x4 = '910526'
x5 = 'M'
x6 = '251221'
x7 = 'GEO'
x8 = 'MAMEDOV'
x9 = 'IUKSEL'
x10 ='10011051644'

text = TD1CodeGenerator(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,force=False)

print(text)

text.optional_data1 = "10001051644"
print()
print(text) 
```

```
IDGEO13IN30572210011051644<<<<
9105263M2512211GEO<<<<<<<<<<<3
MAMEDOV<<IUKSEL<<<<<<<<<<<<<<<

IDGEO13IN30572210001051644<<<<
9105263M2512211GEO<<<<<<<<<<<0
MAMEDOV<<IUKSEL<<<<<<<<<<<<<<<
```

Regards!
