### ISSUE TITLE
How to pip install latest version MRZ?

### ISSUE THREAD

**Issue by junyang-cynopsis** [Arg0s1080/mrz#7]
Hi, the mrz checker module works great! However, I would like to pip install the latest version of mrz which includes the fields() function. How do I do so?

**Comment by Arg0s1080** [comment]
Hi @junyang-cynopsis ,

[Readme.md explains how to install mrz by cloning this repo](https://github.com/Arg0s1080/mrz#cloning-this-repo-it-may-not-work-fine), so I guess some error has occurred. If so, it would be fine to know the error and your OS.

Note: 
- Requires having `git` installed. Optionally you can [download a zip file](https://github.com/Arg0s1080/mrz/archive/master.zip), then unzip and run `python3 setup.py install` in `mrz-master` folder

However, if you can wait, I hope to upload the project to Pypi this afternoon (6-12 hours approx.). Then you can use `pip` or `pip3`

Best regards

**Comment by Arg0s1080** [comment]
It's done.. mrz 0.5.5 is uploaded to PyPi. `pip install mrz` should work
